#########################################################################
# Title:            Sandbox: Sure                                       #
# Author(s):        blekbala                                            #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

sure_name: sure

################################
# Settings
################################

# PostgreSQL
sure_postgres_name: "{{ sure_name }}-postgres"
sure_postgres_docker_env_db: "maybe_production"
sure_postgres_docker_image_tag: "16"
sure_postgres_docker_image_repo: "postgres"
sure_postgres_paths_folder: "{{ sure_name }}"
sure_postgres_paths_location: "{{ server_appdata_path }}/{{ sure_postgres_paths_folder }}/postgres"


################################
# Paths
################################

sure_paths_folder: "{{ sure_name }}"
sure_paths_location: "{{ server_appdata_path }}/{{ sure_paths_folder }}"
sure_paths_folders_list:
  - "{{ sure_paths_location }}"

################################
# Web
################################

sure_web_subdomain: "{{ sure_name }}"
sure_web_domain: "{{ user.domain }}"
sure_web_port: "3000"
sure_web_url: "{{ 'https://' + (sure_web_subdomain + '.' + sure_web_domain 
                if (sure_web_subdomain | length > 0) 
                else sure_web_domain) }}"

sure_web_container: "{{ sure_name }}-web"

################################
# DNS
################################

sure_dns_record: "{{ sure_web_subdomain }}"
sure_dns_zone: "{{ sure_web_domain }}"
sure_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

sure_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
sure_traefik_middleware_default: "{{ traefik_default_middleware }}"
sure_traefik_middleware_custom: ""
sure_traefik_certresolver: "{{ traefik_default_certresolver }}"
sure_traefik_enabled: true
sure_traefik_api_enabled: false
sure_traefik_api_endpoint: ""

################################
# Docker
################################

# Container
sure_docker_container: "{{ sure_name }}"

# Image
sure_docker_image_pull: true
sure_docker_image_tag: "latest"
sure_docker_image: "ghcr.io/we-promise/sure:{{ sure_docker_image_tag }}"

# Ports
sure_docker_ports_defaults: []
sure_docker_ports_custom: []
sure_docker_ports: "{{ sure_docker_ports_defaults 
                   + sure_docker_ports_custom }}"

# Envs
sure_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  SELF_HOSTED: "true"
  RAILS_FORCE_SSL: "false"
  RAILS_ASSUME_SSL: "false"
  GOOD_JOB_EXECUTION_MODE: "async"
  SECRET_KEY_BASE: "{{ sure_saltbox_facts.facts.secret_key_base }}"
  DB_USERNAME: "{{ postgres_docker_env_user }}"
  DB_PASSWORD: "{{ postgres_docker_env_password }}"
  DB_HOST: "{{ sure_postgres_name }}"
  DB_PORT: "5432"
  POSTGRES_USER: "{{ sure_db_user }}"
  POSTGRES_PASSWORD: "{{ sure_db_password }}"
  REDIS_URL: "redis://{{ sure_redis_name }}:6379/1"
  POSTGRES_DB: "{{ sure_db_name }}"
  OPENAI_ACCESS_TOKEN: ""
sure_docker_envs_custom: {}
sure_docker_envs: "{{ sure_docker_envs_default 
                  | combine(sure_docker_envs_custom) }}"

# Commands
sure_docker_commands_default: []
sure_docker_commands_custom: []
sure_docker_commands: "{{ sure_docker_commands_default 
                      + sure_docker_commands_custom }}"

# Volumes
sure_docker_volumes_default:
  - "{{ sure_paths_location }}:/rails/storage"
sure_docker_volumes_custom: []
sure_docker_volumes: "{{ sure_docker_volumes_default 
                     + sure_docker_volumes_custom }}"

# Devices
sure_docker_devices_default: []
sure_docker_devices_custom: []
sure_docker_devices: "{{ sure_docker_devices_default 
                     + sure_docker_devices_custom }}"

# Hosts
sure_docker_hosts_default: {}
sure_docker_hosts_custom: {}
sure_docker_hosts: "{{ docker_hosts_common 
                   | combine(sure_docker_hosts_default) 
                   | combine(sure_docker_hosts_custom) }}"

# Labels
sure_docker_labels_default: {}
sure_docker_labels_custom: {}
sure_docker_labels: "{{ docker_labels_common 
                    | combine(sure_docker_labels_default) 
                    | combine(sure_docker_labels_custom) }}"

# Hostname
sure_docker_hostname: "{{ sure_name }}"

# Networks
sure_docker_networks_alias: "{{ sure_name }}"
sure_docker_networks_default: []
sure_docker_networks_custom: []
sure_docker_networks: "{{ docker_networks_common 
                      + sure_docker_networks_default 
                      + sure_docker_networks_custom }}"

# Capabilities
sure_docker_capabilities_default: []
sure_docker_capabilities_custom: []
sure_docker_capabilities: "{{ sure_docker_capabilities_default 
                          + sure_docker_capabilities_custom }}"

# Security Opts
sure_docker_security_opts_default: []
sure_docker_security_opts_custom: []
sure_docker_security_opts: "{{ sure_docker_security_opts_default 
                           + sure_docker_security_opts_custom }}"

# Restart Policy
sure_docker_restart_policy: unless-stopped

# State
sure_docker_state: started

# Dependencies
sure_depends_on: "{{ sure_postgres_name }}"
sure_depends_on_delay: "5"
sure_depends_on_healthchecks: "true"
