#########################################################################
# Title:           Sandbox: Sure                                        #
# Author(s):       blekbala                                             #
# URL:             https://github.com/saltyorg/Sandbox                  #
# --                                                                    #
#########################################################################
#                  GNU General Public License v3.0                     #
#########################################################################
- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
  loop:
    - "{{ sure_name }}"
    - "{{ sure_name }}-worker"
    - "{{ sure_name }}-redis"

- name: Generate Secret Key Base
  community.docker.docker_container:
    name: sure-secret-key
    image: "{{ sure_docker_image }}"
    command: "sh -c 'head -c 32 /dev/urandom | base64'"
    detach: no
    networks:
      - name: saltbox
    cleanup: yes
    state: started
    container_default_behavior: compatibility
    tls_hostname: localhost
    pull: true
  register: sure_generated_secret_key

- name: "Save sure Secret Key Base Saltbox facts"
  saltbox_facts:
    role: "sure"
    instance: "sure"
    keys:
      secret_key_base: "{{ sure_generated_secret_key.container.Output }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  register: sure_saltbox_facts

- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"
    dns_proxy: "{{ lookup('vars', role_name + '_dns_proxy') }}"

- name: Import Redis Role
  ansible.builtin.include_role:
    name: redis
  vars:
    redis_instances: ["{{ sure_name }}-redis"]
    redis_paths_folder: "{{ sure_name }}"
    redis_paths_location: "{{ server_appdata_path }}/{{ redis_paths_folder }}/redis"

- name: Import PostgreSQL Role
  ansible.builtin.include_role:
    name: postgres
  vars:
    postgres_instances: ["{{ sure_postgres_name }}"]
    postgres_docker_env_db: "{{ sure_postgres_docker_env_db }}"
    postgres_docker_image_tag: "{{ sure_postgres_docker_image_tag }}"
    postgres_docker_image_repo: "{{ sure_postgres_docker_image_repo }}"
    postgres_paths_folder: "{{ sure_postgres_paths_folder }}"
    postgres_paths_location: "{{ sure_postgres_paths_location }}"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: "Import Sure Worker Role"
  ansible.builtin.include_role:
    name: sure_worker
